### ISSUE TITLE
Microsoft Teams doesn't work

### ISSUE THREAD

**Issue by Braintelligence** [TheGoddessInari/hamsket#129] opened 2019-09-27 08:33 UTC
### Steps to reproduce

1. Use Hamsket 0.5.19 with left side bar
2. Set up Microsoft Teams
3. See blank page with a blue line

### Expected behavior

Be able to use MS Teams

### Actual behavior

Can't use MS Teams because blank page

### ENVIRONMENT

> Hamsket: v0.5.19

> OS: Win10 64 Build 18362

> Does this happen upstream: unknown

**Comment by SyntaxErrol** [comment] 2019-10-10 13:02
For me it does work right after first setting it up but after shutting down and relaunching Hamsket, it's that blank page. To get it to work again, I have to delete and re-add the service. This issue also exists in Rambox CE.

**Comment by Lomanic** [comment] 2019-10-19 23:26
Looks like a duplicate of TheGoddessInari#120 to me. Do you still reproduce if you append `Object.defineProperty(navigator.serviceWorker,"register",{value:()=>Promise.reject()});`to your custom JS for this service?

**Comment by LiBOSS-CZ** [comment] 2019-10-20 13:38
I had similar problem, but I do not get blank page but I get message that informs me to sign out and sign in again. Custom JS from above seems to solve the problem

**Comment by TheGoddessInari** [comment] 2019-10-20 17:07
Duplicate of #120 
I'll push out a `0.5.20` as well as the nightly today for a workaround.

**Closed by TheGoddessInari** 2019-10-20 17:07 UTC
