### ISSUE TITLE
[Feature request] Add custom user agent

### ISSUE THREAD

**Issue by Pciuggo** [TheGoddessInari/hamsket#126] opened 2019-09-01 16:13 UTC
I saw Rambox CE had this option, i would love to use your fork since is open source but i really need this feature.

**Comment by TheGoddessInari** [comment] 2019-09-01 17:06
I'll look into it since I have to deal with user-agent stuff anyway to fix stupid webapps (WhatsApp and Outlook 365 on Linux, apparently).

Part of the problem is that there's hardly any UI space for options, and I'm really not a UI designer, so I'm not sure how to do fancy tricks, especially with such an ancient toolkit as ExtJS 5.

I'll work on it ASAP, though. I might have to make stuff into separate tabs or something. 🦊

**Comment by TheGoddessInari** [comment] 2019-09-01 17:13
Also, do you have a pull request pending?

**Comment by Pciuggo** [comment] 2019-09-01 20:41
Oh i understand i hope you can solve this, wish i could be helpful, i wanted to ask if the tabs are sandboxed for each webapp you use?
apart from this if yo don't mind reply i saw other software you make and i was wondering if you learned programming through coursera :)

**Comment by TheGoddessInari** [comment] 2019-09-01 23:07
The tabs are isolated from each other to some degree, but Electron (the code that underpins this, Rambox CE, Franz, Slack, Discord, and almost every other similar app) isn't meant to run arbitrary code, and doesn't have a true security model.

I'm doing what I can to make things better than upstream ever allowed, but my resources on that are (at best) limited to what Electron allows.

It'd be better to have full sandboxing mode, full context isolation, etc, but that'd require a lot of extra work with IPC that I'm not quite prepared to get into yet. I'm always happy to accept help there.

I'm nearly done working on the User Agent stuff, just trying to get the UI to work nicely at this point.

I learned programming by myself in the mid-1990s by taking apart [MUDs](https://en.wikipedia.org/wiki/MUD) and putting them back together again. :P It was the same to learn javascript. I wanted something fixed, upstream refused to fix it, I fixed it, even though I didn't know javascript at the time.

**Comment by Pciuggo** [comment] 2019-09-02 00:09
That's nice at least there is some isolation :D I understand now, i hope i can contribute someday since i'm planning to learn electron framework which i find really amazing for bringing so many desktop app, especially for linux! I asked you about coursera since i'm planning to learn programming and i thought you were learning from there :P What do you suggest for a beginner? for know i know html css and a basic python, Planning to get some certificate soon

**Comment by TheGoddessInari** [comment] 2019-09-02 01:51
I would just be happier if I could figure out the UI stuff better now.

Electron is a nightmare to work with, IMO.

I'd seriously recommend literally any other programming language, any other framework, for desktop development.

Modern C++, Rust, F#, and C# aren't that hard to learn, IMO. Rust is the only one with less mature GUI support (but it is kinda the language of the future).

For programming languages, I tend to just learn by doing. Computer Science and programming fundamentals are probably more or less required for that, though.

Try the `useragent-fix` temporary branch. I may manually make executables from Azure based on it.

**Comment by TheGoddessInari** [comment] 2019-09-02 02:07
Builds are available on here for now. https://dev.azure.com/TheGoddessInari/hamsket/_build/results?buildId=125&view=results

**Comment by Pciuggo** [comment] 2019-09-03 14:22
thanks a lot i appreciate your advice :D for cs i'm studying from here https://github.com/ossu/computer-science if you have any other reccomandation would be nice :D and thanks for the build!

**Comment by Pciuggo** [comment] 2019-09-06 10:58
@TheGoddessInari is there a way to spoof os platform? even if i changed usera agent, it still shows that 'm using linux :(

**Comment by TheGoddessInari** [comment] 2019-09-06 11:14
Yes, try this version. 

https://dev.azure.com/TheGoddessInari/hamsket/_build/results?buildId=128&view=artifacts

It has both the user agent field and the selector.

I need to figure out some UI problems before it can be merged, namely, how to deal with the case where a particular service always needs an override (like apparently Outlook 365), but make it clearer to the user with what's happening than "if I set things back to blank, it reappears with an override".

**Comment by TheGoddessInari** [comment] 2019-10-29 18:25
It is per-service right now. I don't have a general "global" option, and I'm working on the UI to figure out how to represent displaying a shipped (preset) override that you (the user) can change, so the UI isn't confusing.

**Comment by MurzNN** [comment] 2019-10-30 08:29
I can't find where in current nightly (commit ce44d75) I can fill per-service custom user agent string (and global too), @TheGoddessInari  - can you point to right place? Thanks!

**Comment by MurzNN** [comment] 2019-10-30 08:31
Ow, seems this feature is in separate `useragent-fix` branch, that not yet merged in nightly.

**Comment by TheGoddessInari** [comment] 2019-10-30 13:27
Right, the builds are generally available over here until it's merged.

https://dev.azure.com/TheGoddessInari/hamsket/_build?definitionId=6&_a=summary

For instance, the artifacts from that particular commit are over here if you're not signed in/not on the "new UI" for Azure DevOps. :)

https://dev.azure.com/TheGoddessInari/hamsket/_build/results?buildId=163&view=results

**Comment by Anzuul** [comment] 2020-01-08 06:42
I needed to switch to the `useragent-fix` branch to fix the "This browser or app may not be secure" issue with Gmail. Seems like there is at least one other person with the same issue so far, and it seems like it might eventually effect a lot more people. #159 
https://support.google.com/accounts/thread/22873505?hl=en

**Comment by TheGoddessInari** [comment] 2020-03-03 20:01
Merged as of 3d16baa.
Everything should be working as of f347f53.

**Closed by TheGoddessInari** 2020-03-03 20:01 UTC
