### ISSUE TITLE
Whatsapp freezes after playing video

### ISSUE THREAD

**Issue by LiBOSS-CZ** [TheGoddessInari/hamsket#99] opened 2019-05-18 06:57 UTC
### Steps to reproduce

1. Click on play on the youtube video link in Whatsapp
2. Started to play in embedded window
3. Close this embedded window

### Expected behavior

Everything works after closing embedded video window. 

### Actual behavior

Whatsapp freeezes and you have to restart rambox

### ENVIRONMENT

> Rambox-OS: v0.5.18

> OS: Windows 10 Pro 1809

> Arch: x64

> BuildVersion: 26702dc

**Comment by TheGoddessInari** [comment] 2019-06-02 20:29
Does it work to right click and reload the tab instead of restarting Rambox?

Because of how this is working (it freezes on pause as well, and just freezes the rendering/view in that tab), it **looks** to be a bug or misconfiguration in Electron 5.x.

**Comment by TheGoddessInari** [comment] 2019-06-02 20:40
It looks like we're hitting both electron/electron#17890 and electron/electron#18177. :/

**Comment by TheGoddessInari** [comment] 2019-07-25 00:35
Please recheck this. It looks fixed currently, so I'll close it as fixed in a few days if there's not more reproduction of the issue. :)

**Comment by LiBOSS-CZ** [comment] 2019-07-25 04:42
I have tried it and seems to be OK.

**Closed** 2019-08-01 13:38 UTC

**Comment by TheGoddessInari** [comment] 2019-08-01 13:40
This was fixed in one of the Electron 5.0.x point updates, but I don't have time to pin down exactly which one right now.
