### ISSUE TITLE
HTML instead of name in titlebar (slack)

### ISSUE THREAD

**Issue by micw** [TheGoddessInari/hamsket#228] opened 2020-10-08 07:58 UTC
### Steps to reproduce

Unfortunately, I dod not figure out how to reproduce the issue. From time to time, the titlebar in hamsket shows some html on one of my slack account (see screenshot):
![Screenshot](https://user-images.githubusercontent.com/186753/95430948-c740a880-094c-11eb-8f98-be1ef3f20b96.png)

When I edit or disable/enable the account, it's normal again.

### ENVIRONMENT

> Hamsket: v0.6.0

> OS: Linux

> Arch: x64

> BuildVersion: 9ab646e (grafted, HEAD, tag: nightly, origin/master) Mon, 3 Aug 2020 08:19:02 -0700

> Does this happen upstream: unknown, or N/A

**Comment by jsangeorzan** [comment] 2020-10-13 19:25
Hello! I reported this here: https://github.com/TheGoddessInari/hamsket/issues/225

**Comment by TheGoddessInari** [comment] 2020-11-03 03:49
Right, which is why that's a dupe of #225 and you should have just bumped that. Sorry. I can't begin to describe why things have been so hard on me lately, nor would it be appropriate. Expect this to get fixed soon.

**Closed by TheGoddessInari** 2020-11-03 03:49 UTC
