### ISSUE TITLE
(Bug) Gmail Can't Sign In

### ISSUE THREAD

**Issue by Locked-Key** [TheGoddessInari/hamsket#173] opened 2020-03-01 03:53 UTC
### Steps to reproduce

1. Select Gmail
2. Sign In
3. Gmail will say this browser isn't secure.

### Expected behavior

Gmail can sign in

### Actual behavior

Gmail warns that the browser isn't secure and doesn't let you log in

### ENVIRONMENT

> Hamsket: 0.6.0

> OS: win32 (x64)

> BuildVersion: 37d2be1 (grafted, HEAD, tag: nightly, origin/master) Mon, 24 Feb 2020 10:13:07 -0800

> Does this happen upstream: N/A

**Comment by TheGoddessInari** [comment] 2020-03-03 18:06
This is a duplicate of #159. I should get the fix merged today barring unforeseen complications.

**Closed by TheGoddessInari** 2020-03-03 18:06 UTC
