### ISSUE TITLE
Skype Audio and Video Calls are disabled 

### ISSUE THREAD

**Issue by MDJ-GitHub1** [TheGoddessInari/hamsket#233] opened 2020-10-26 18:25 UTC
1-Launching Hamsket
        2-Adding Skype Service and Opening it up
        => both audio and video are grayed out 

	
	-
	> Hamsket 0.6.0
	> Electron 10.1.4
	> win32 x64 10.0.19041
	> 06c8aef  (grafted, HEAD, tag: nightly, origin/master) Thu, 22 Oct 2020 12:41:26 -0700

**Comment by username02** [comment] 2020-10-27 04:52
> ```
> 1-Launching Hamsket
>     2-Adding Skype Service and Opening it up
>     => both audio and video are grayed out 
> ```

See issue #213

**Comment by TheGoddessInari** [comment] 2020-10-28 06:20
Right, closing this as a duplicate of #213. I'm actively trying to figure this out, but it's not making a whole lot of sense unless it's something truly Weird on Electron's end.

Please, do feel free to comment further in #213. I'm happy that people are trying to pin this down.

**Closed by TheGoddessInari** 2020-10-28 06:20 UTC
